### ISSUE TITLE
"Klippy-State: disconnected" after commit cc63fd

### ISSUE THREAD

**Issue by carlmorgan** [Klipper3d/klipper#4788]
Breaking merge on master - Stock 3B+ rPi / MainsailOS / Moonraker - based of mainsailos-rpi-lite-0.5.0 / buster / fulling patched

Valid / working config pre update, re-producable forward and back revving. 

Fails after commit cc63fd, Mon Oct 4 15:09:10 2021 -0400    scripts: Use backport of a recent Python3 configparser on Python2

I think key line in klipper.log:
File "/home/pi/moonraker/moonraker/websockets.py", line 224, in execute_method result = await method(conn, *args, **kwargs)
==snip==
utils.ServerError: {'message': "Extrude below minimum temp\nSee the 'min_extrude_temp' config option for details", 'error': 'WebRequestError'}

[ Discord: https://discord.com/channels/431557959978450984/801826273227177984/895920741483184198 - Contribution from JamesH#3255 - Checked, no obvious UTF8 / extended ascii characters in config. ]

**Comment by carlmorgan** [comment]
Sorry - didn't fix it....

After pull to up to date (21d5a34), re-compiled BTT Mini e3 v2 firmware and transferred it.
Used ~/klipper/config/generic-bigtreetech-skr-mini-e3-v2.0.cfg default config
Klipper process now not running at all - and no klipper.log generated.

From syslog.
Oct  9 14:02:53 voron-v0 systemd[1]: klipper.service: Service RestartSec=10s expired, scheduling restart.
Oct  9 14:02:53 voron-v0 systemd[1]: klipper.service: Scheduled restart job, restart counter is at 28.
Oct  9 14:02:53 voron-v0 systemd[1]: Stopped Starts Klipper and provides klippy Unix Domain Socket API.
Oct  9 14:02:53 voron-v0 systemd[1]: Started Starts Klipper and provides klippy Unix Domain Socket API.
Oct  9 14:02:53 voron-v0 python[3838]: Traceback (most recent call last):
Oct  9 14:02:53 voron-v0 python[3838]:   File "/home/pi/klipper/klippy/klippy.py", line 9, in <module>
Oct  9 14:02:53 voron-v0 python[3838]:     import gcode, configfile, pins, mcu, toolhead, webhooks
Oct  9 14:02:53 voron-v0 python[3838]:   File "/home/pi/klipper/klippy/configfile.py", line 6, in <module>
Oct  9 14:02:53 voron-v0 python[3838]:     import os, glob, re, time, logging, configparser, io
Oct  9 14:02:53 voron-v0 python[3838]: ImportError: No module named configparser

pi@voron-v0:~/klippy-env $ . bin/activate
(klippy-env) pi@voron-v0:~/klippy-env $ pip freeze
aenum==3.1.0
cffi==1.12.2
greenlet==0.4.15
Jinja2==2.11.3
MarkupSafe==1.1.1
numpy==1.16.6
pkg-resources==0.0.0
pycparser==2.20
pyserial==3.4
python-can==3.3.4
typing==3.10.0.0
wrapt==1.12.1

**Comment by carlmorgan** [comment]
Fixed via Discord - py2 env hadn't pulled in new requirements.

sudo systemctl stop klipper
 ~/klippy-env/bin/pip install -r ~/klipper/scripts/klippy-requirements.txt
sudo systemctl start klipper

Fixed it / running again with master and original config.
