### ISSUE TITLE
PID_CALIBRATE throws error with Python3

### ISSUE THREAD

**Issue by kpishere** [Klipper3d/klipper#5389]
When issuing the
```
PID_CALIBRATE HEATER=extruder TARGET=200 WRITE_FILE=1
```
 with klipper running with Python3, there is an error when writing the file as follows 

```
ADS1x1: Read 0x20 Volts 0.359 Scale 0.1100 Temp 200.053
Autotune: raw=-9.361497/1.000000 Ku=0.272016 Tu=9.891990  Kp=41.618483 Ki=8.414582 Kd=51.461204
Stats 1290222.0: gcodein=0 mcu: mcu_awake=0.002 mcu_task_avg=0.000003 mcu_task_stddev=0.000005 bytes_write=277668 bytes_read=307337 bytes_retransmit=9 bytes_invalid=0 send_seq=26633 receive_seq=26633 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=1000045  sysload=2.39 cputime=59.678 print_time=597.987 buffer_time=0.185 print_stall=0 extruder: target=195 temp=200.1 pwm=0.000
ADS1x1: Read 0x20 Volts 0.359 Scale 0.1100 Temp 200.053
Internal error on command:"PID_CALIBRATE"
Traceback (most recent call last):
  File "/klipper-update-toPython3/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/klipper-update-toPython3/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/klipper-update-toPython3/klippy/extras/pid_calibrate.py", line 35, in cmd_PID_CALIBRATE
    calibrate.write_file('/tmp/heattest.txt')
  File "/klipper-update-toPython3/klippy/extras/pid_calibrate.py", line 140, in write_file
    f.write('\n'.join(pwm + out))
TypeError: a bytes-like object is required, not 'str'
Transition to shutdown state: Internal error on command:"PID_CALIBRATE"
Dumping gcode input 0 blocks
Dumping 12 requests for client 4457253904
```
  
The fix is as follows : 

```
diff --git a/klippy/extras/pid_calibrate.py b/klippy/extras/pid_calibrate.py
index f269a373..f32f1be7 100644
--- a/klippy/extras/pid_calibrate.py
+++ b/klippy/extras/pid_calibrate.py
@@ -136,7 +136,7 @@ class ControlAutoTune:
         pwm = ["pwm: %.3f %.3f" % (time, value)
                for time, value in self.pwm_samples]
         out = ["%.3f %.3f" % (time, temp) for time, temp in self.temp_samples]
-        f = open(filename, "wb")
+        f = open(filename, "w")
         f.write('\n'.join(pwm + out))
         f.close()
 
```

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit c08f83ff).

-Kevin
